name: license-manager-simulator
base: core20
version: '0.1'
summary: Simulate a license management server output.
description: |
  Use this snap to simulate a license server http endpoint.

grade: stable
confinement: strict

apps:
  license-manager-simulator:
    daemon: simple
    command: bin/uwsgi --processes 4 --threads 2 --http :9999 --wsgi-file $SNAP/app.py
    plugs: [network, network-bind]

  license-manager-generator:
    daemon: oneshot
    timer: "00:00-24:00/1440"
    command: ./license_manager_generator.py

parts:
  license-manager-simulator:
    plugin: dump
    source: src/license-manager-simulator/

  python:
    plugin: python
    python-packages:
      - wheel
      - uwsgi
      - jinja2

    stage-packages:
      - libpython3.8

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/
