name: "Test"

on: pull_request
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint check
        run: |
          pip install tox
          make lint
